import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import StoreProvider from "./StoreProvider";
import theme from "./theme";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fintess Partner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-4 bg-slate-50`}>
        <div className="flex justify-center w-full">
          <div className="flex flex-col justify-center w-4/5">
            <AppRouterCacheProvider>
              <StoreProvider>
                <ThemeProvider theme={theme}>{children}</ThemeProvider>
              </StoreProvider>
            </AppRouterCacheProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
