import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { ConfigProvider, Flex } from "antd";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "./components/Navigation/page";
import OutletWrapper from "./components/OutletWrapper";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import theme from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fintess Partner",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-0 m-0`}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#202020FF",
              },
            }}
          >
            <StoreProvider>
              <Flex vertical justify="flex-start">
                <Navigation />
                <AppRouterCacheProvider>
                  <ThemeProvider theme={theme}>
                    <OutletWrapper>{children}</OutletWrapper>
                  </ThemeProvider>
                </AppRouterCacheProvider>
              </Flex>
            </StoreProvider>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
