export const list: WorkoutItem[] = [
  {
    id: 1,
    title: "Walking Lunges",
    execriseTimes: 60,
    restTimes: 30,
    set: 2,
    prepareTimes: 10,
    requiredItem: {
      time: 60,
      rest: 30,
      prepare: 10,
      set: 2,
    },
  },
  {
    id: 2,
    title: "Burpees",
    execriseTimes: 60,
    restTimes: 30,
    set: 2,
    prepareTimes: 10,
    requiredItem: {
      time: 60,
      rest: 30,
      prepare: 10,
      set: 2,
    },
  },
  {
    id: 3,
    title: "Jumping Jacks",
    execriseTimes: 60,
    restTimes: 30,
    set: 2,
    prepareTimes: 10,
    requiredItem: {
      time: 60,
      rest: 30,
      prepare: 10,
      set: 2,
    },
  },
  {
    id: 4,
    title: "Mountain Climbers",
    execriseTimes: 60,
    restTimes: 30,
    set: 2,
    prepareTimes: 10,
    requiredItem: {
      time: 60,
      rest: 30,
      prepare: 10,
      set: 2,
    },
  },
  {
    id: 5,
    title: "High Knees",
    execriseTimes: 60,
    restTimes: 30,
    set: 2,
    prepareTimes: 10,
    requiredItem: {
      time: 60,
      rest: 30,
      prepare: 10,
      set: 2,
    },
  },
  {
    id: 6,
    title: "Butt Kicks",
    execriseTimes: 60,
    restTimes: 30,
    set: 2,
    prepareTimes: 10,
    requiredItem: {
      time: 60,
      rest: 30,
      prepare: 10,
      set: 2,
    },
  },
  {
    id: 7,
    title: "Skaters",
    execriseTimes: 60,
    restTimes: 30,
    set: 2,
    prepareTimes: 10,
    requiredItem: {
      time: 60,
      rest: 30,
      prepare: 10,
      set: 2,
    },
  },
  {
    id: 8,
    title: "Plank Jacks",
    execriseTimes: 60,
    restTimes: 30,
    set: 2,
    prepareTimes: 10,
    requiredItem: {
      time: 60,
      rest: 30,
      prepare: 10,
      set: 2,
    },
  },
];
